spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: carden-flashcards
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Default database configuration (for when no profile is active)
  datasource:
    url: jdbc:postgresql://localhost:5432/carden_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /api

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGY=}
    access-token-expiration: PT60M # 60 minutes (longer for now)
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200,http://localhost:5173}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

